# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: OlivierZal/configs/.github/workflows/dependabot.yml@140fc08403302560b9ae86c2aa7970ffe88e7c71 # v1.1.0
name: dependabot
on:
  pull_request: {}
permissions: {}
