# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  pr_title:
    permissions:
      pull-requests: read
    uses: OlivierZal/configs/.github/workflows/pr-title.yml@140fc08403302560b9ae86c2aa7970ffe88e7c71 # v1.1.0
name: pr-title
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
permissions: {}
